config/routes.rb
Rails.application.routes.draw do
 
  root "home#index"
  get  "about", to: "pages#about"
  get  "mission", to: "pages#mission"
  get  "tariffs", to: "pages#tariffs"
  get  "services", to: "pages#services"
  get  "magazine", to: "pages#magazine"
  get  "contacts", to: "pages#contacts"
  get  "privacy_policy", to: "pages#privacy_policy"

  get "dashboard", to: "profiles#dashboard"
  get "dashboard/brand", to: "profiles#brand"
  get "dashboard/area", to: "profiles#area"
  
  post "profiles/edit", to: "profiles#update"

  resources :areas
  resources :brands
  resources :gigs

  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq)
end

app/views/shared/header/_navbar.html.erb
<!-- Navbar-->
<header class="navbar navbar-expand-lg navbar-light bg-light fixed-top" data-scroll-header>
  <div class="container px-3">
    <%= link_to root_path, class: "navbar-brand me-3 me-xl-4", data: {turbo: "false"} do %>
      <%= image_tag 'logo.png', class: "d-block" %>
    <% end %>
    <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if rodauth.logged_in? %>
      <div class="order-lg-3 my-n2">
        <%= link_to dashboard_path, class: "btn btn-sm btn-outline-secondary px-2 py-1 d-flex align-items-center", data: {turbo: "false"}  do %>
          <i class="uil uil-bell me-2 fa-lg"></i>
          <%= image_tag 'noavatar.png', class: "rounded-circle border", width: "30" %>
        <% end %>
      </div>
    <% else %>
      <div class="order-lg-3 my-n2">
        <%= link_to rodauth.login_path, class: "btn btn-sm btn-outline-secondary px-2 py-1 d-flex align-items-center", data: {turbo: "false"}  do %>
          <i class="uil uil-signin me-2 fa-lg"></i>
          <%= image_tag 'noavatar.png', class: "rounded-circle border", width: "30" %>
        <% end %>
      </div>
    <% end %>
    <div class="collapse navbar-collapse order-lg-2" id="navbarNav">
      <ul class="navbar-nav navbar-nav-scroll" style="max-height: 35rem;">
        <li class="nav-item"><%= link_to "Миссия", mission_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Рейтинг", brands_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Тарифы", tariffs_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Услуги", services_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Журнал", magazine_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Маркет", gigs_path, class: "nav-link" %></li>
      </ul>
    </div>
  </div>
</header>