config/routes.rb
Rails.application.routes.draw do
 
  root "home#index"
  get  "about", to: "pages#about"
  get  "mission", to: "pages#mission"
  get  "tariffs", to: "pages#tariffs"
  get  "services", to: "pages#services"
  get  "magazine", to: "pages#magazine"
  get  "contacts", to: "pages#contacts"
  get  "privacy_policy", to: "pages#privacy_policy"

  get "dashboard", to: "profiles#dashboard"
  get "dashboard/brand", to: "profiles#brand"
  get "dashboard/area", to: "profiles#area"
  
  post "profiles/edit", to: "profiles#update"

  resources :areas
  resources :brands
  resources :gigs

  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq)
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :bigint           not null, primary key
#  bio        :string
#  firstname  :string
#  lastname   :string
#  username   :string
#  website    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  account_id :bigint           not null
#
# Indexes
#
#  index_profiles_on_account_id  (account_id)
#
# Foreign Keys
#
#  fk_rails_...  (account_id => accounts.id)
#
class Profile < ApplicationRecord
  belongs_to :account

  validates :firstname, presence: true
  validates :lastname, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate
  before_action :set_profile, only: %i[dashboard update]

  def dashboard
    @gigs = current_account.gigs.order("id DESC").all
  end

  def brand
    @brands = current_account.brands.order("id DESC").all
  end

  def area
    @areas = current_account.areas.order("id DESC").all
  end

  def update
    if @profile.update(profile_params)
      flash.now[:notice] = "Профиль успешно обновлен"
    else
      flash.now[:alert] = "Не удалось обновить профиль"
    end
    redirect_to dashboard_path
  end

  private

  def set_profile
    @profile = current_profile
  end

  def profile_params
    params.require(:profile).permit(:username, :firstname, :lastname, :website, :bio, :account_id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_aside.html.erb
<aside class="col-lg-4 col-xl-3 border px-3 rounded mb-4">
  <div class="d-flex d-md-block d-lg-flex align-items-start align-items-center py-4">
    <%= link_to dashboard_path, data: {turbo: "false"}  do %>
      <%= image_tag 'noavatar.png', class: "rounded-circle border", width: "68" %>
    <% end %>
    <div class="pt-md-2 pt-lg-0 ps-3 ps-md-0 ps-lg-3">
      <h3 class="h6 mb-0">
        <%= current_profile.firstname %>
        <%= current_profile.lastname %>
      </h3>
      <span class="star-rating">
        <i class="star-rating-icon fi-star-filled active"></i>
        <i class="star-rating-icon fi-star-filled active"></i>
        <i class="star-rating-icon fi-star-filled active"></i>
        <i class="star-rating-icon fi-star-filled active"></i>
        <i class="star-rating-icon fi-star-filled "></i>
      </span>
    </div>
  </div>
  <div class="row">
    <div class="col-3">
      <button type="button" class="btn btn-outline-secondary w-100 mb-4 px-0" data-bs-toggle="modal" data-bs-target="#settingsModal">
        <i class="uil uil-compass fa-lg"></i>
      </button>
    </div>
    <div class="col-3">
      <button type="button" class="btn btn-outline-secondary w-100 mb-4 px-0" data-bs-toggle="modal" data-bs-target="#settingsModal">
        <i class="uil uil-telegram-alt fa-lg"></i>
      </button>
    </div>
    <div class="col-3">
      <button type="button" class="btn btn-outline-secondary w-100 mb-4 px-0" data-bs-toggle="modal" data-bs-target="#settingsModal">
        <i class="uil uil-edit fa-lg"></i>
      </button>
    </div>
    <div class="col-3">
      <%= link_to rodauth.logout_path, data: { turbo_method: :post }, class: "btn btn-outline-secondary w-100 mb-4 px-0"  do %>
        <i class="uil uil-signout fa-lg"></i>
      <% end %>
    </div>
  </div>
  <div class="modal fade" id="settingsModal" tabindex="-1" aria-labelledby="settingsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="h6 modal-title" id="settingsModalLabel">Редактировать</h3>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= form_for :profile, url: profiles_edit_url, action: :update, method: :post do |form| %>
          <div class="modal-body">
            <div class="mb-4">
              <%= form.label :firstname, "Имя", class: "form-label" %>
              <%= form.text_field :firstname, class: "form-control" %>
            </div>
            <div class="mb-4">
              <%= form.label :lastname, "Фамилия", class: "form-label" %>
              <%= form.text_field :lastname, class: "form-control" %>
            </div>
            <div class="mb-4">
              <%= form.label :bio, "О себе", class: "form-label" %>
              <%= form.text_area :bio, rows:"6", class: "form-control" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            <%= form.submit "Сохранить", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="offcanvas offcanvas-start offcanvas-collapse" id="filters-sidebar">
    <div class="offcanvas-header d-flex d-lg-none align-items-center">
      <h3 class="h6 mb-0">Меню</h3>
      <button class="btn-close" type="button" data-bs-dismiss="offcanvas"></button>
    </div>
    <div class="offcanvas-body">
      <div class="mb-4">
        <h3 class="h6 fs-base">Товарищества и участки</h3>
        <div class="card-nav">
          <%= link_to  dashboard_brand_path, class: current_class?(dashboard_brand_path), data: {turbo: "false"} do %>
            <i class="uil uil-trees fa-lg me-2"></i>
            <strong class="fs-sm ">Мои товарищества</strong>
          <% end %>
          <%= link_to  dashboard_area_path, class: current_class?(dashboard_area_path), data: {turbo: "false"} do %>
            <i class="uil uil-house-user fa-lg me-2"></i>
            <strong class="fs-sm ">Мои участки</strong>
          <% end %>
        </div>
      </div>
      <div class="pb-4 mb-2">
        <h3 class="h6 fs-base">Вход и безопасность</h3>
        <div class="card-nav">
          <%= link_to  rodauth.change_password_path, class: current_class?(rodauth.change_password_path), data: {turbo: "false"} do %>
            <i class="uil uil-unlock-alt fa-lg me-2"></i>
            <strong class="fs-sm ">Изменить пароль</strong>
          <% end %>
          <%= link_to  rodauth.change_login_path, class: current_class?(rodauth.change_login_path), data: {turbo: "false"} do %>
            <i class="uil uil-envelope-redo fa-lg me-2"></i>
            <strong class="fs-sm ">Изменить email</strong>
          <% end %>
          <%= link_to  rodauth.close_account_path, class: current_class?(rodauth.close_account_path), data: {turbo: "false"} do %>
            <i class="uil uil-trash-alt fa-lg me-2"></i>
            <strong class="fs-sm ">Удалить аккаунт</strong>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</aside>

app/views/profiles/_aside_public.html.erb
<aside class="col-lg-4 col-xl-3 border px-3 rounded mb-4">
  <div class="d-flex d-md-block d-lg-flex align-items-start align-items-center py-4">
    <%= link_to dashboard_path, data: {turbo: "false"}  do %>
      <%= image_tag 'noavatar.png', class: "rounded-circle border", width: "68" %>
    <% end %>
    <div class="pt-md-2 pt-lg-0 ps-3 ps-md-0 ps-lg-3">
      <h3 class="h6 mb-0">
        <%= model.account.profile.firstname  %>
        <%= model.account.profile.lastname  %>
      </h3>
      <span class="star-rating">
        <i class="star-rating-icon fi-star-filled active"></i>
        <i class="star-rating-icon fi-star-filled active"></i>
        <i class="star-rating-icon fi-star-filled active"></i>
        <i class="star-rating-icon fi-star-filled active"></i>
        <i class="star-rating-icon fi-star-filled "></i>
      </span>
      <ul class="list-unstyled fs-sm mt-3 mb-0">
        <li><a class="nav-link fw-normal p-0" href="tel:3025550107">
            <i class="fi-phone opacity-60 me-2"></i>(302) 555-0107</a>
        </li>
        <li>
          <a class="nav-link fw-normal p-0" href="mailto:annette_black@email.com">
            <i class="fi-mail opacity-60 me-2"></i>annette_black@email.com
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <button type="button" class="btn btn-outline-secondary w-100 mb-4 px-0" data-bs-toggle="modal" data-bs-target="#settingsModal">
        <i class="uil uil-telegram-alt fa-lg me-2"></i>
        Сообщение
      </button>
    </div>
  </div>
  <div class="modal fade" id="settingsModal" tabindex="-1" aria-labelledby="settingsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="h6 modal-title" id="settingsModalLabel">Отправить сообщение</h3>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= form_for :profile, url: nil, action: :update, method: :post do |form| %>
          <div class="modal-body">
            <div class="mb-4">
              <%= form.label :bio, "Ваше сообщение", class: "form-label" %>
              <%= form.text_area :bio, rows:"6", class: "form-control" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            <%= form.submit "Отправить", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="offcanvas offcanvas-start offcanvas-collapse" id="filters-sidebar">
    <div class="offcanvas-header d-flex d-lg-none align-items-center">
      <h3 class="h6 mb-0">Отправить запрос</h3>
      <button class="btn-close" type="button" data-bs-dismiss="offcanvas"></button>
    </div>
    <div class="offcanvas-body">
      <div class="pb-4 mb-2">
      </div>
    </div>
  </div>
</aside>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_field :bio %>
  </div>

  <div>
    <%= form.label :account_id, style: "display: block" %>
    <%= form.text_field :account_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <p>
    <strong>Username:</strong>
    <%= profile.username %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= profile.name %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= profile.website %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= profile.bio %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= profile.account_id %>
  </p>

</div>

app/views/profiles/area.html.erb
<% provide(:title, "Мой участок") %>
<div class="container mt-5 pt-5">
  <div class="row g-0 mt-n3">
    <%= render 'profiles/aside' %>
    <!-- Page content-->
    <div class="col-lg-8 col-xl-9 position-relative overflow-hidden pb-5 px-3">
      <div class="d-flex flex-sm-row flex-column align-items-sm-center align-items-stretch">
        <div class="d-flex align-items-center flex-shrink-0">
          <%= link_to new_area_path, class: "btn btn-outline-secondary" do %>
            <i class="uil uil-plus fa-lg me-2"></i>
            Создать
          <% end %>
        </div>
        <hr class="d-none d-sm-block w-100 mx-4">
        <div class="d-none d-sm-flex align-items-center flex-shrink-0 text-muted">
          <i class="fi-check-circle me-2"></i>
          <span class="fs-sm ">всего 0 участков</span>
        </div>
      </div>
      <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h3 class="h6 modal-title" id="addModalLabel">Новая публикация</h3>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>
      <!-- Catalog grid-->
      <div class="row g-4 py-4" id="gigs">
        <!-- Item-->
        <% @areas.each do |area| %>
          <%= render area %>
        <% end %>
      </div>
      <!-- Pagination-->
      <nav class="border-top pb-md-4 pt-4 mt-2" aria-label="Pagination">
        <ul class="pagination mb-1">
          <li class="page-item d-sm-none"><span class="page-link page-link-static">1 / 5</span></li>
          <li class="page-item active d-none d-sm-block" aria-current="page"><span class="page-link">1<span class="visually-hidden">(current)</span></span></li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">2</a></li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">3</a></li>
          <li class="page-item d-none d-sm-block">...</li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">8</a></li>
          <li class="page-item"><a class="page-link" href="real-estate-catalog-rent.html#" aria-label="Next"><i class="fi-chevron-right"></i></a></li>
        </ul>
      </nav>
    </div>
  </div>
</div>
<button class="btn btn-primary btn-sm w-100 rounded-0 fixed-bottom d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#filters-sidebar">
  Меню
</button>

app/views/profiles/brand.html.erb
<% provide(:title, "Мое товарищество") %>
<div class="container mt-5 pt-5">
  <div class="row g-0 mt-n3">
    <%= render 'profiles/aside' %>
    <!-- Page content-->
    <div class="col-lg-8 col-xl-9 position-relative overflow-hidden pb-5 px-3">
      <div class="d-flex flex-sm-row flex-column align-items-sm-center align-items-stretch">
        <div class="d-flex align-items-center flex-shrink-0">
          <%= link_to new_brand_path, class: "btn btn-outline-secondary" do %>
            <i class="uil uil-plus fa-lg me-2"></i>
            Создать
          <% end %>
        </div>
        <hr class="d-none d-sm-block w-100 mx-4">
        <div class="d-none d-sm-flex align-items-center flex-shrink-0 text-muted">
          <i class="fi-check-circle me-2"></i>
          <span class="fs-sm ">всего 0 публикаций</span>
        </div>
      </div>
      <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h3 class="h6 modal-title" id="addModalLabel">Новая публикация</h3>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>
      <!-- Catalog grid-->
      <div class="row g-4 py-4" id="gigs">
        <!-- Item-->
        <% @brands.each do |brand| %>
          <%= render brand %>
        <% end %>
      </div>
      <!-- Pagination-->
      <nav class="border-top pb-md-4 pt-4 mt-2" aria-label="Pagination">
        <ul class="pagination mb-1">
          <li class="page-item d-sm-none"><span class="page-link page-link-static">1 / 5</span></li>
          <li class="page-item active d-none d-sm-block" aria-current="page"><span class="page-link">1<span class="visually-hidden">(current)</span></span></li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">2</a></li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">3</a></li>
          <li class="page-item d-none d-sm-block">...</li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">8</a></li>
          <li class="page-item"><a class="page-link" href="real-estate-catalog-rent.html#" aria-label="Next"><i class="fi-chevron-right"></i></a></li>
        </ul>
      </nav>
    </div>
  </div>
</div>
<button class="btn btn-primary btn-sm w-100 rounded-0 fixed-bottom d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#filters-sidebar">
  Меню
</button>

app/views/profiles/dashboard.html.erb
<% provide(:title, "Главная") %>
<div class="container mt-5 pt-5">
  <div class="row g-0 mt-n3">
    <%= render 'profiles/aside' %>
    <!-- Page content-->
    <div class="col-lg-8 col-xl-9 position-relative overflow-hidden pb-5 px-3">
      <div class="d-flex flex-sm-row flex-column align-items-sm-center align-items-stretch">
        <div class="d-flex align-items-center flex-shrink-0">
          <%= link_to new_gig_path, class: "btn btn-outline-secondary" do %>
            <i class="uil uil-plus fa-lg me-2"></i>
            Создать
          <% end %>
        </div>
        <hr class="d-none d-sm-block w-100 mx-4">
        <div class="d-none d-sm-flex align-items-center flex-shrink-0 text-muted">
          <i class="fi-check-circle me-2"></i>
          <span class="fs-sm ">всего 0 публикаций</span>
        </div>
      </div>
      <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h3 class="h6 modal-title" id="addModalLabel">Новая публикация</h3>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>
      <!-- Catalog grid-->
      <div class="row g-4 py-4" id="gigs">
        <!-- Item-->
        <% @gigs.each do |gig| %>
          <%= render gig %>
        <% end %>
      </div>
      <!-- Pagination-->
      <nav class="border-top pb-md-4 pt-4 mt-2" aria-label="Pagination">
        <ul class="pagination mb-1">
          <li class="page-item d-sm-none"><span class="page-link page-link-static">1 / 5</span></li>
          <li class="page-item active d-none d-sm-block" aria-current="page"><span class="page-link">1<span class="visually-hidden">(current)</span></span></li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">2</a></li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">3</a></li>
          <li class="page-item d-none d-sm-block">...</li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">8</a></li>
          <li class="page-item"><a class="page-link" href="real-estate-catalog-rent.html#" aria-label="Next"><i class="fi-chevron-right"></i></a></li>
        </ul>
      </nav>
    </div>
  </div>
</div>
<button class="btn btn-primary btn-sm w-100 rounded-0 fixed-bottom d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#filters-sidebar">
  Меню
</button>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Show this profile", @profile %> |
  <%= link_to "Back to profiles", profiles_path %>
</div>