config/routes.rb
Rails.application.routes.draw do
 
  root "home#index"
  get  "about", to: "pages#about"
  get  "mission", to: "pages#mission"
  get  "tariffs", to: "pages#tariffs"
  get  "services", to: "pages#services"
  get  "magazine", to: "pages#magazine"
  get  "contacts", to: "pages#contacts"
  get  "privacy_policy", to: "pages#privacy_policy"

  get "dashboard", to: "profiles#dashboard"
  get "dashboard/brand", to: "profiles#brand"
  get "dashboard/area", to: "profiles#area"
  
  post "profiles/edit", to: "profiles#update"

  resources :areas
  resources :brands
  resources :gigs

  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq)
end

app/models/area.rb
# == Schema Information
#
# Table name: areas
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  number      :string
#  square      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  account_id  :bigint           not null
#  brand_id    :bigint           not null
#
# Indexes
#
#  index_areas_on_account_id  (account_id)
#  index_areas_on_brand_id    (brand_id)
#
# Foreign Keys
#
#  fk_rails_...  (account_id => accounts.id)
#  fk_rails_...  (brand_id => brands.id)
#
class Area < ApplicationRecord
  belongs_to :brand
  belongs_to :account
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :authenticate, only: %i[new edit update destroy]
  before_action :set_area, only: %i[show edit update destroy]
  before_action :append_regions, only: %i[index new edit]
  before_action :append_categories, only: %i[index new edit]
  before_action :append_brands, only: %i[index new edit]

  def index
    @areas = Area.all
  end

  def show
  end

  def new
    @area = current_account.areas.new
  end

  def edit
  end

  def create
    @area = current_account.areas.new(area_params)

    if @area.save
      redirect_to dashboard_brand_path
      flash[:notice] = "Участок успешно создан"
    else
      flash.now[:alert] = "Не удалось создать участок"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @area.update(area_params)
      redirect_to @area, notice: "Area was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @area.destroy
    redirect_to areas_url, notice: "Area was successfully destroyed."
  end

  private

  def set_area
    @area = Area.find(params[:id])
  end

  def append_regions
    @regions = Region.all
  end

  def append_categories
    @categories = Category.all
  end

  def append_brands
    @brands = Brand.all
  end

  def area_params
    params.require(:area).permit(:name, :description, :square, :number, :brand_id, :account_id)
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_area.html.erb
<div class="col-sm-6 col-xl-4" id="<%= dom_id area %>">
  <div class="card card-hover border-0 border-top border-start border-end border-bottom h-100">
    <div class="tns-carousel-wrapper card-img-top card-img-hover">
      <a class="img-overlay" href="<%= area_url(area) %>"></a>
      <div class="content-overlay end-0 top-0 pt-3 pe-3">
        <button class="btn btn-icon btn-light btn-xs text-primary rounded-circle" type="button" data-bs-toggle="tooltip" data-bs-placement="left" title="В избранное">
          <i class="uil uil-heart"></i>
        </button>
      </div>
      <div class="tns-carousel-inner">
        <img src="<%= image_url('nophotos.png') %>" width="500" height="500" alt="Image">
        <img src="<%= image_url('nophotos.png') %>" width="500" height="500"  alt="Image">
      </div>
    </div>
    <div class="card-body position-relative pb-3 border-top">
      <div class="text-truncate">
        <h3 class="h6 mb-2 fs-base">
          <a class="nav-link stretched-link" href="<%= area_url(area) %>"><%= area.name %></a>
        </h3>
        <p class="mb-2 fs-sm d-flex align-items-center">
          <%= image_tag 'russia.svg', class: "me-2", width: "20"  %>
          <%= area.brand.region.name_with_type  %>
        </p>
      </div>
    </div>
    <div class="card-footer d-flex align-items-center px-3 pt-3">
      <div class="d-inline-block fs-sm d-flex align-items-center">
        <i class="fi-bed ms-1 fs-lg text-muted"></i>
        <span class="mx-3">1</span>
      </div>
      <div class="d-inline-block fs-sm d-flex align-items-center">
        <i class="fi-bed ms-1 fs-lg text-muted"></i>
        <span class="mx-3">1</span>
      </div>
      <div class="d-inline-block fs-sm d-flex align-items-center">
        <i class="fi-bed ms-1 fs-lg text-muted"></i>
        <span class="mx-3">1</span>
      </div>
    </div>
    <% if current_page?(dashboard_area_path) %>
      <div class="card-footer d-flex align-items-center px-3 pt-3 justify-content-between">
        <%= link_to  edit_area_path(area), class: "btn btn-outline-secondary btn-icon" do %>
          <i class="uil uil-edit"></i>
        <% end %>
        <%= button_to  area_path(area), method: :delete, class: "btn btn-outline-danger btn-icon" do %>
          <i class="uil uil-trash-alt"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/areas/_form.html.erb
<%= form_with(model: area) do |form| %>
  <div class="mb-4">
    <%= form.label :brand_id, "Товарищество", class: "form-label" %>
    <%= form.collection_select :brand_id, @brands, :id, :name, {:include_blank => true}, {class: "form-control"} %>
  </div>
  <div class="mb-4">
    <%= form.label :name, "Название", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="mb-4">
    <%= form.label :description, "Описание", class: "form-label" %>
    <%= form.text_area :description, rows: "6", class: "form-control" %>
  </div>
  <div class="mb-4">
    <%= form.label :square, "Площадь", class: "form-label" %>
    <%= form.text_field :square, class: "form-control" %>
  </div>
  <div class="mb-4">
    <%= form.label :number, "Номер", class: "form-label" %>
    <%= form.text_field :number, class: "form-control" %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing area</h1>

<%= render "form", area: @area %>

<br>

<div>
  <%= link_to "Show this area", @area %> |
  <%= link_to "Back to areas", areas_path %>
</div>

app/views/areas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Areas</h1>

<div id="areas">
  <% @areas.each do |area| %>
    <%= render area %>
    <p>
      <%= link_to "Show this area", area %>
    </p>
  <% end %>
</div>

<%= link_to "New area", new_area_path %>

app/views/areas/new.html.erb
<% provide(:title, "Новый участок") %>
<div class="container mt-5 pt-5">
  <div class="row g-0 mt-n3">
    <%= render 'profiles/aside' %>
    <!-- Page content-->
    <div class="col-lg-8 col-xl-9 position-relative overflow-hidden pb-5 px-3">
      <div class="d-flex flex-sm-row flex-column align-items-sm-center align-items-stretch">
        <div class="d-flex align-items-center flex-shrink-0">
          <%= link_to dashboard_path, class: "btn btn-outline-secondary" do %>
            <i class="uil uil-arrow-left fa-lg me-2"></i>
            Назад
          <% end %>
        </div>
        <hr class="d-none d-sm-block w-100 mx-4">
        <div class="d-none d-sm-flex align-items-center flex-shrink-0 text-muted">
          <i class="uil uil-exclamation-circle fa-lg me-2"></i>
          <span class="fs-sm ">Внимание</span>
        </div>
      </div>
      <!-- Catalog grid-->
      <div class="row g-4 py-4">
        <!-- Item-->
        <div class="col-12">
          <%= render "form", area: @area %>
        </div>
      </div>
    </div>
  </div>
</div>
<button class="btn btn-primary btn-sm w-100 rounded-0 fixed-bottom d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#filters-sidebar">
  Меню
</button>

app/views/areas/show.html.erb
<% provide(:title, "") %>
<div class="container mt-5 pt-5">
  <div class="row g-0 mt-n3">
    <%= render 'profiles/aside_public', :model => @area %>
    
    <!-- Page content-->
    <div class="col-lg-8 col-xl-9 position-relative overflow-hidden pb-5 px-3">
      <div class="d-flex flex-sm-row flex-column align-items-sm-center align-items-stretch">
        <div class="d-flex align-items-center flex-shrink-0">
          <%= link_to :back, class: "btn btn-outline-secondary" do %>
            <i class="uil uil-arrow-left fa-lg me-2"></i>
            Назад
          <% end %>
        </div>
        <hr class="d-none d-sm-block w-100 mx-4">
        <div class="d-none d-sm-flex align-items-center flex-shrink-0 text-muted">
          <i class="uil uil-exclamation-circle fa-lg me-2"></i>
          <span class="fs-sm ">Внимание</span>
        </div>
      </div>
      <!-- Catalog grid-->
      <div class="row g-4 py-4">
        <div class="col-lg-8">
          <div class="d-flex flex-column">
            <!-- Carousel with slides count-->
            <div class="order-lg-1 order-2">
              <div class="tns-carousel-wrapper">
                <div class="tns-slides-count text-light">
                  <i class="fi-image fs-lg me-2"></i>
                  <div class="ps-1">
                    <span class="tns-current-slide fs-5 fw-bold"></span>
                    <span class="fs-5 fw-bold">/</span>
                    <span class="tns-total-slides fs-5 fw-bold"></span>
                  </div>
                </div>
                <div class="tns-carousel-inner" data-carousel-options="{&quot;navAsThumbnails&quot;: true, &quot;navContainer&quot;: &quot;#thumbnails&quot;, &quot;gutter&quot;: 12, &quot;responsive&quot;: {&quot;0&quot;:{&quot;controls&quot;: false},&quot;500&quot;:{&quot;controls&quot;: true}}}">
                  <div><img src="<%= image_url('nophotos.png') %>" class="rounded-3" alt="Image"></div>
                  <div><img src="<%= image_url('nophotos.png') %>" class="rounded-3" alt="Image"></div>
                  <div><img src="<%= image_url('nophotos.png') %>" class="rounded-3" alt="Image"></div>
                  <div><img src="<%= image_url('nophotos.png') %>" class="rounded-3" alt="Image"></div>
                  <div><img src="<%= image_url('nophotos.png') %>" class="rounded-3" alt="Image"></div>
                </div>
              </div>
              <!-- Thumbnails nav-->
              <ul class="tns-thumbnails mb-4" id="thumbnails">
                <li class="tns-thumbnail"><img src="<%= image_url('nophotos.png') %>" class="tns-thumbnail" alt="Image"></li>
                <li class="tns-thumbnail"><img src="<%= image_url('nophotos.png') %>" class="tns-thumbnail" alt="Image"></li>
                <li class="tns-thumbnail"><img src="<%= image_url('nophotos.png') %>" class="tns-thumbnail" alt="Image"></li>
                <li class="tns-thumbnail"><img src="<%= image_url('nophotos.png') %>" class="tns-thumbnail" alt="Image"></li>
                <li class="tns-thumbnail"><img src="<%= image_url('nophotos.png') %>" class="tns-thumbnail" alt="Image"></li>
              </ul>
            </div>
            <!-- Page title + Features-->
            <div class="order-2">
              <h1 class="h6 mb-4"> <%= @area.name %> </h1>
              <p class="mb-4 d-flex align-items-center pb-1">
                <%= image_tag 'russia.svg', class: "me-2", width: "25"  %>
                <%= @area.brand.region.name_with_type  %>
              </p>
              <ul class="d-flex mb-4 pb-lg-2 list-unstyled">
                <li class="me-3 pe-3 border-end"><b class="me-1">4</b><i class="fi-bed mt-n1 lead align-middle text-muted"></i></li>
                <li class="me-3 pe-3 border-end"><b class="me-1">2</b><i class="fi-bath mt-n1 lead align-middle text-muted"></i></li>
                <li class="me-3 pe-3 border-end"><b class="me-1">2</b><i class="fi-car mt-n1 lead align-middle text-muted"></i></li>
                <li><b>56 </b>sq.m</li>
              </ul>
            </div>
          </div>
          <p class="mb-4 pb-2">
            
          </p>
        </div>
        <!-- Sidebar with details-->
        <aside class="col-lg-4">
          <!-- Property details-->
          
        </aside>
      </div>
    </div>
  </div>
</div>
<button class="btn btn-primary btn-sm w-100 rounded-0 fixed-bottom d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#filters-sidebar">
  Меню
</button>