config/routes.rb
Rails.application.routes.draw do
 
  root "home#index"
  get  "about", to: "pages#about"
  get  "mission", to: "pages#mission"
  get  "tariffs", to: "pages#tariffs"
  get  "services", to: "pages#services"
  get  "magazine", to: "pages#magazine"
  get  "contacts", to: "pages#contacts"
  get  "privacy_policy", to: "pages#privacy_policy"

  get "dashboard", to: "profiles#dashboard"
  get "dashboard/brand", to: "profiles#brand"
  get "dashboard/area", to: "profiles#area"
  
  post "profiles/edit", to: "profiles#update"

  resources :areas
  resources :brands
  resources :gigs

  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq)
end

app/models/brand.rb
# == Schema Information
#
# Table name: brands
#
#  id          :bigint           not null, primary key
#  address     :string
#  description :text
#  email       :string
#  geo_lat     :string
#  geo_lon     :string
#  inn         :string
#  name        :string
#  ogrn        :string
#  phone       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  account_id  :bigint           not null
#  region_id   :bigint           not null
#
# Indexes
#
#  index_brands_on_account_id  (account_id)
#  index_brands_on_region_id   (region_id)
#
# Foreign Keys
#
#  fk_rails_...  (account_id => accounts.id)
#  fk_rails_...  (region_id => regions.id)
#
class Brand < ApplicationRecord
  belongs_to :region
  belongs_to :account
  has_many :areas

  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :inn, presence: true
  validates :ogrn, presence: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate, only: %i[new edit update destroy]
  before_action :set_brand, only: %i[show edit update destroy]
  before_action :append_regions, only: %i[index new edit]
  before_action :append_categories, only: %i[index new edit]

  def index
    @q = Brand.ransack(params[:q])
    @brands = @q.result(distinct: true)
  end

  def show
  end

  def new
    @brand = current_account.brands.new
  end

  def edit
  end

  def create
    @brand = current_account.brands.new(brand_params)

    if @brand.save
      redirect_to dashboard_brand_path
      flash[:notice] = "Товарищество успешно создано"
    else
      flash.now[:alert] = "Не удалось создать товарищество"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @brand.update(brand_params)
      redirect_to @brand, notice: "Brand was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @brand.destroy
    redirect_to brands_url, notice: "Brand was successfully destroyed."
  end

  private

  def set_brand
    @brand = Brand.find(params[:id])
  end

  def append_regions
    @regions = Region.all
  end

  def append_categories
    @categories = Category.all
  end

  def brand_params
    params.require(:brand).permit(
      :name,
      :description,
      :phone,
      :email,
      :inn,
      :ogrn,
      :region_id,
      :address,
      :geo_lat,
      :geo_lon,
      :account_id
    )
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_brand.html.erb
<div class="col-sm-6 col-xl-4" id="<%= dom_id brand %>">
  <div class="card card-hover border-0 border-top border-start border-end border-bottom h-100">
    <div class="tns-carousel-wrapper card-img-top card-img-hover">
      <a class="img-overlay" href="<%= brand_url(brand) %>"></a>
      <div class="content-overlay end-0 top-0 pt-3 pe-3">
        <button class="btn btn-icon btn-light btn-xs text-primary rounded-circle" type="button" data-bs-toggle="tooltip" data-bs-placement="left" title="В избранное">
          <i class="uil uil-heart"></i>
        </button>
      </div>
      <div class="tns-carousel-inner">
        <img src="<%= image_url('nophotos.png') %>" width="500" height="500" alt="Image">
        <img src="<%= image_url('nophotos.png') %>" width="500" height="500"  alt="Image">
      </div>
    </div>
    <div class="card-body position-relative pb-3 border-top">
      <div class="text-truncate">
        <h3 class="h6 mb-2 fs-base">
          <a class="nav-link stretched-link" href="<%= brand_url(brand) %>"><%= brand.name %></a>
        </h3>
        <p class="mb-2 fs-sm d-flex align-items-center">
          <%= image_tag 'russia.svg', class: "me-2", width: "20"  %>
          <%= brand.region.name_with_type  %>
        </p>
      </div>
    </div>
    <div class="card-footer d-flex align-items-center px-3 pt-3">
      <div class="d-inline-block fs-sm d-flex align-items-center">
        <i class="fi-bed ms-1 fs-lg text-muted"></i>
        <span class="mx-3">1</span>
      </div>
      <div class="d-inline-block fs-sm d-flex align-items-center">
        <i class="fi-bed ms-1 fs-lg text-muted"></i>
        <span class="mx-3">1</span>
      </div>
      <div class="d-inline-block fs-sm d-flex align-items-center">
        <i class="fi-bed ms-1 fs-lg text-muted"></i>
        <span class="mx-3">1</span>
      </div>
    </div>
    <% if current_page?(dashboard_brand_path) %>
      <div class="card-footer d-flex align-items-center px-3 pt-3 justify-content-between">
        <%= link_to  edit_brand_path(brand), class: "btn btn-outline-secondary btn-icon" do %>
          <i class="uil uil-edit"></i>
        <% end %>
        <%= button_to  brand_path(brand), method: :delete, class: "btn btn-outline-danger btn-icon" do %>
          <i class="uil uil-trash-alt"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <div class="mb-4">
    <%= form.label :region_id, "Регион", class: "form-label" %>
    <%= form.collection_select :region_id, @regions, :id, :name, {:include_blank => true}, {class: "form-control"} %>
  </div>
  <div class="mb-4">
    <%= form.label :address, "Адрес", class: "form-label" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>
  <div class="mb-4">
    <%= form.label :name, "Название", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="mb-4">
    <%= form.label :description, "Описание", class: "form-label" %>
    <%= form.text_area :description, rows: "6", class: "form-control" %>
  </div>
  <div class="mb-4">
    <%= form.label :phone, "Телефон", class: "form-label" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>
  <div class="mb-4">
    <%= form.label :email, "Email", class: "form-label" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="mb-4">
    <%= form.label :inn, "ИНН", class: "form-label" %>
    <%= form.text_field :inn, class: "form-control" %>
  </div>
  <div class="mb-4">
    <%= form.label :ogrn, "ОГРН", class: "form-label" %>
    <%= form.text_field :ogrn, class: "form-control" %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Show this brand", @brand %> |
  <%= link_to "Back to brands", brands_path %>
</div>

app/views/brands/index.html.erb
<% provide(:title, "Поиск по рейтингу") %>
<!-- Page container-->
<div class="container mt-5 pt-5">
  <div class="row g-0 mt-n3">
    <!-- Filters sidebar (Offcanvas on mobile)-->
    <aside class="col-lg-4 col-xl-3 border px-3 rounded mb-4">
      <div class="offcanvas offcanvas-start offcanvas-collapse" id="filters-sidebar">
        <%= search_form_for @q do |form| %>
          <div class="offcanvas-header d-flex d-lg-none align-items-center">
            <h2 class="h5 mb-0">Поиск</h2>
            <button class="btn-close" type="button" data-bs-dismiss="offcanvas"></button>
          </div>
          <div class="offcanvas-body py-lg-4">
            <div class="pb-4 mb-2">
              <h3 class="h6">Регион</h3>
              <%= form.collection_select :region_id_eq, @regions, :id, :name, {:include_blank => true}, {class: "form-control"} %>
            </div>
            <div class="border-top py-4">
              <%= form.submit "Найти", class: "btn btn-outline-primary w-100" %>
            </div>
          </div>
        </div>
      <% end %>
    </aside>
    <!-- Page content-->
    <div class="col-lg-8 col-xl-9 position-relative overflow-hidden pb-5 px-3">
      <!-- Map popup-->
      <div class="map-popup invisible" id="map">
        <button class="btn btn-icon btn-light btn-sm shadow-sm rounded-circle" type="button" data-bs-toggle-class="invisible" data-bs-target="#map"><i class="fi-x fs-xs"></i></button>
        <div class="interactive-map" data-map-options-json="json/map-options-real-estate-rent.json"></div>
      </div>
      <div class="d-flex flex-sm-row flex-column align-items-sm-center align-items-stretch">
        <div class="d-flex align-items-center flex-shrink-0">
          <a class="btn btn-outline-secondary" href="real-estate-catalog-rent.html#" data-bs-toggle-class="invisible" data-bs-target="#map">
            <i class="fi-map me-2"></i>
            На карте
          </a>
        </div>
        <hr class="d-none d-sm-block w-100 mx-4">
        <div class="d-none d-sm-flex align-items-center flex-shrink-0 text-muted">
          <i class="fi-check-circle me-2"></i>
          <span class="fs-sm ">Более 1000 вариантов</span>
        </div>
      </div>
      <div class="card card-hover card-horizontal border-0 shadow-sm mb-4"><a class="card-img-top" href="real-estate-single-v1.html" style="background-image: url(img/real-estate/catalog/08.jpg);">
          <div class="position-absolute start-0 top-0 pt-3 ps-3"><span class="d-table badge bg-info">New</span></div>
        </a>
        <div class="card-body position-relative pb-3">
          <div class="dropdown position-absolute zindex-5 top-0 end-0 mt-3 me-3">
          </div>
          <h4 class="mb-1 fs-xs fw-normal text-uppercase text-primary">For rent</h4>
          <h3 class="h6 mb-2 fs-base"><a class="nav-link stretched-link" href="real-estate-single-v1.html">Greenpoint Rentals | 85 sq.m</a></h3>
          <p class="mb-2 fs-sm text-muted">1510 Castle Hill Ave Bronx, NY 10462</p>
          <div class="fw-bold">
            <span class="star-rating">
              <i class="star-rating-icon fi-star-filled active"></i>
              <i class="star-rating-icon fi-star-filled active"></i>
              <i class="star-rating-icon fi-star-filled active"></i>
              <i class="star-rating-icon fi-star-filled active"></i>
              <i class="star-rating-icon fi-star-filled "></i>
            </span>
          </div>
          <div class="d-flex align-items-center justify-content-center justify-content-sm-start border-top pt-3 pb-2 mt-3 text-nowrap"><span class="d-inline-block me-4 fs-sm">1<i class="fi-bed ms-1 mt-n1 fs-lg text-muted"></i></span><span class="d-inline-block me-4 fs-sm">1<i class="fi-bath ms-1 mt-n1 fs-lg text-muted"></i></span><span class="d-inline-block fs-sm">1<i class="fi-car ms-1 mt-n1 fs-lg text-muted"></i></span></div>
        </div>
      </div>
      <!-- Catalog grid-->
      <div class="row g-4 py-4" id="gigs">
        <!-- Item-->
        <% @brands.each do |brand| %>
          <%= render brand %>
        <% end %>
      </div>
      <!-- Pagination-->
      <nav class="border-top pb-md-4 pt-4 mt-2" aria-label="Pagination">
        <ul class="pagination mb-1">
          <li class="page-item d-sm-none"><span class="page-link page-link-static">1 / 5</span></li>
          <li class="page-item active d-none d-sm-block" aria-current="page"><span class="page-link">1<span class="visually-hidden">(current)</span></span></li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">2</a></li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">3</a></li>
          <li class="page-item d-none d-sm-block">...</li>
          <li class="page-item d-none d-sm-block"><a class="page-link" href="real-estate-catalog-rent.html#">8</a></li>
          <li class="page-item"><a class="page-link" href="real-estate-catalog-rent.html#" aria-label="Next"><i class="fi-chevron-right"></i></a></li>
        </ul>
      </nav>
    </div>
  </div>
</div>
<!-- Sidebar toggle button (mobile)-->
<button class="btn btn-primary btn-sm w-100 rounded-0 fixed-bottom d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#filters-sidebar">
  <i class="fi-filter me-2"></i>
  Поиск
</button>

app/views/brands/new.html.erb
<% provide(:title, "Новое товарищество") %>
<div class="container mt-5 pt-5">
  <div class="row g-0 mt-n3">
    <%= render 'profiles/aside' %>
    <!-- Page content-->
    <div class="col-lg-8 col-xl-9 position-relative overflow-hidden pb-5 px-3">
      <div class="d-flex flex-sm-row flex-column align-items-sm-center align-items-stretch">
        <div class="d-flex align-items-center flex-shrink-0">
          <%= link_to dashboard_path, class: "btn btn-outline-secondary" do %>
            <i class="uil uil-arrow-left fa-lg me-2"></i>
            Назад
          <% end %>
        </div>
        <hr class="d-none d-sm-block w-100 mx-4">
        <div class="d-none d-sm-flex align-items-center flex-shrink-0 text-muted">
          <i class="uil uil-exclamation-circle fa-lg me-2"></i>
          <span class="fs-sm ">Внимание</span>
        </div>
      </div>
      <!-- Catalog grid-->
      <div class="row g-4 py-4">
        <!-- Item-->
        <div class="col-12">
          <%= render "form", brand: @brand %>
        </div>
      </div>
    </div>
  </div>
</div>
<button class="btn btn-primary btn-sm w-100 rounded-0 fixed-bottom d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#filters-sidebar">
  Меню
</button>

app/views/brands/show.html.erb
<% provide(:title, "") %>
<div class="container mt-5 pt-5">
  <div class="row g-0 mt-n3">
    <%= render 'profiles/aside_public', :model => @brand %>
    
    <!-- Page content-->
    <div class="col-lg-8 col-xl-9 position-relative overflow-hidden pb-5 px-3">
      <div class="d-flex flex-sm-row flex-column align-items-sm-center align-items-stretch">
        <div class="d-flex align-items-center flex-shrink-0">
          <%= link_to :back, class: "btn btn-outline-secondary" do %>
            <i class="uil uil-arrow-left fa-lg me-2"></i>
            Назад
          <% end %>
        </div>
        <hr class="d-none d-sm-block w-100 mx-4">
        <div class="d-none d-sm-flex align-items-center flex-shrink-0 text-muted">
          <i class="uil uil-exclamation-circle fa-lg me-2"></i>
          <span class="fs-sm ">Внимание</span>
        </div>
      </div>
      <!-- Catalog grid-->
      <div class="row g-4 py-4">
        <div class="col-lg-8">
          <div class="d-flex flex-column">
            <!-- Carousel with slides count-->
            <div class="order-lg-1 order-2">
              <div class="tns-carousel-wrapper">
                <div class="tns-slides-count text-light">
                  <i class="fi-image fs-lg me-2"></i>
                  <div class="ps-1">
                    <span class="tns-current-slide fs-5 fw-bold"></span>
                    <span class="fs-5 fw-bold">/</span>
                    <span class="tns-total-slides fs-5 fw-bold"></span>
                  </div>
                </div>
                <div class="tns-carousel-inner" data-carousel-options="{&quot;navAsThumbnails&quot;: true, &quot;navContainer&quot;: &quot;#thumbnails&quot;, &quot;gutter&quot;: 12, &quot;responsive&quot;: {&quot;0&quot;:{&quot;controls&quot;: false},&quot;500&quot;:{&quot;controls&quot;: true}}}">
                  <div><img src="<%= image_url('nophotos.png') %>" class="rounded-3" alt="Image"></div>
                  <div><img src="<%= image_url('nophotos.png') %>" class="rounded-3" alt="Image"></div>
                  <div><img src="<%= image_url('nophotos.png') %>" class="rounded-3" alt="Image"></div>
                  <div><img src="<%= image_url('nophotos.png') %>" class="rounded-3" alt="Image"></div>
                  <div><img src="<%= image_url('nophotos.png') %>" class="rounded-3" alt="Image"></div>
                </div>
              </div>
              <!-- Thumbnails nav-->
              <ul class="tns-thumbnails mb-4" id="thumbnails">
                <li class="tns-thumbnail"><img src="<%= image_url('nophotos.png') %>" class="tns-thumbnail" alt="Image"></li>
                <li class="tns-thumbnail"><img src="<%= image_url('nophotos.png') %>" class="tns-thumbnail" alt="Image"></li>
                <li class="tns-thumbnail"><img src="<%= image_url('nophotos.png') %>" class="tns-thumbnail" alt="Image"></li>
                <li class="tns-thumbnail"><img src="<%= image_url('nophotos.png') %>" class="tns-thumbnail" alt="Image"></li>
                <li class="tns-thumbnail"><img src="<%= image_url('nophotos.png') %>" class="tns-thumbnail" alt="Image"></li>
              </ul>
            </div>
            <!-- Page title + Features-->
            <div class="order-2">
              <h1 class="h6 mb-4"> <%= @brand.name %> </h1>
              <p class="mb-4 d-flex align-items-center pb-1">
                <%= image_tag 'russia.svg', class: "me-2", width: "25"  %>
                <%= @brand.region.name_with_type  %>
              </p>
              <ul class="d-flex mb-4 pb-lg-2 list-unstyled">
                <li class="me-3 pe-3 border-end"><b class="me-1">4</b><i class="fi-bed mt-n1 lead align-middle text-muted"></i></li>
                <li class="me-3 pe-3 border-end"><b class="me-1">2</b><i class="fi-bath mt-n1 lead align-middle text-muted"></i></li>
                <li class="me-3 pe-3 border-end"><b class="me-1">2</b><i class="fi-car mt-n1 lead align-middle text-muted"></i></li>
                <li><b>56 </b>sq.m</li>
              </ul>
            </div>
          </div>
          <p class="mb-4 pb-2">
            
          </p>
        </div>
        <!-- Sidebar with details-->
        <aside class="col-lg-4">
          <!-- Property details-->
          
        </aside>
      </div>
    </div>
  </div>
</div>
<button class="btn btn-primary btn-sm w-100 rounded-0 fixed-bottom d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#filters-sidebar">
  Вступить в товарищество
</button>